#
# These settings are for the database used by the Metasploit Framework
# unstable tree included in this installer, not the commercial editions.
#
development:
  adapter: "postgresql"
  database: "msf"
  username: "msf"
  password: "msf"
  port: 5432
  host: "localhost"
  pool: 256
  timeout: 5

production:
  adapter: "postgresql"
  database: "msf"
  username: "msf"
  password: "msf"
  port: 5432
  host: "localhost"
  pool: 256
  timeout: 5

