#!/bin/sh
#THIS IS A GRUB PROXY SCRIPT
'/etc/grub.d/proxifiedScripts/linux' | /etc/grub.d/bin/grubcfg_proxy "+*
+'Arch Linux, with Linux linux-mzn (fallback initramfs)'~a4400f739e247b9b52e8a74c6c8e9bc1~
+'Arch Linux, with Linux linux-lts'~13858636afef0c304d38bd63e67a2c66~
+'Arch Linux, with Linux linux-lts (fallback initramfs)'~667522cb767b22def2e51864b14f0acb~
+'Arch Linux, with Linux linux-ck-nehalem'~818aa1f6e88c8a88bddc9c22de1c69d5~
+'Arch Linux, with Linux linux-ck-nehalem (fallback initramfs)'~bdc52dd9ea27c3a5ea4b683de9ae5fed~
+#text
+'Arch Linux, with Linux linux-mzn'~745f5bd6de8cc9c9d9e04e589eeb2b02~ as 'Arch Linux'
"