#!/bin/sh
#THIS IS A GRUB PROXY SCRIPT
'/etc/grub.d/proxifiedScripts/linux' | /etc/grub.d/bin/grubcfg_proxy "+*
+'Arch Linux, with Linux linux-ck'~67ec9c65879378cda5dc53e25e61b82d~
+'Arch Linux, with Linux linux-ck (fallback initramfs)'~e0814ff7ef88008b923ca42b92c2f799~
+'Arch Linux, with Linux linux'~d91343270bea2db24a6209bbd16af6ad~
+'Arch Linux, with Linux linux (fallback initramfs)'~f0682c4c5c1d3f08969b4ac1078d1d11~
+'Arch Linux, with Linux linux-lts'~7aa14c89e7b864d60080a8e9f47121c3~
+'Arch Linux, with Linux linux-lts (fallback initramfs)'~ce6962b6dcb70969f644cd33050aa89c~
+#text
"